---
# handlers file for install-k8s
- name: Restart Docker
  systemd: 
    state: restarted 
    daemon_reload: yes
    name: docker
    
- name: Restart Kubelet
  systemd: 
    state: restarted
    daemon_reload: yes 
    name: kubelet 